set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSROOT $ENV{SDKTARGETSYSROOT})

# 컴파일러 경로(바이너리) 고정
set(CMAKE_C_COMPILER   $ENV{CC_CMAKE})
set(CMAKE_CXX_COMPILER $ENV{CXX_CMAKE})
set(CMAKE_ASM_COMPILER $ENV{CC_CMAKE})

# 플래그 전달(필요 시 sysroot 재확인)
set(CMAKE_C_FLAGS               "${CMAKE_C_FLAGS} $ENV{EXTRA_C_FLAGS} --sysroot=$ENV{SDKTARGETSYSROOT}")
set(CMAKE_CXX_FLAGS             "${CMAKE_CXX_FLAGS} $ENV{EXTRA_CXX_FLAGS} --sysroot=$ENV{SDKTARGETSYSROOT}")
set(CMAKE_EXE_LINKER_FLAGS      "${CMAKE_EXE_LINKER_FLAGS} --sysroot=$ENV{SDKTARGETSYSROOT}")
set(CMAKE_SHARED_LINKER_FLAGS   "${CMAKE_SHARED_LINKER_FLAGS} --sysroot=$ENV{SDKTARGETSYSROOT}")

# shared 빌드
set(BUILD_SHARED_LIBS ON CACHE BOOL "Build shared libs" FORCE)

# .so 우선
set(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a")

set(CMAKE_FIND_ROOT_PATH "$ENV{SDKTARGETSYSROOT}" "$ENV{OPENSSL_ROOT_DIR}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# MagicCrypto/의존성
# DSO(.so)로 링크하면 보통 -lMagicCrypto만으로 충분하지만,
# 환경에 따라 -lmc, -ldl, -lpthread, -lrt 등이 필요할 수 있음
set(CMAKE_C_STANDARD_LIBRARIES "${CMAKE_C_STANDARD_LIBRARIES} -lMagicCrypto -lmc -ldl -lpthread -lz -lrt")
